# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

findRepresent <- function(mt, geno) {
    .Call(`_binmapr_findRepresent`, mt, geno)
}

findWindow <- function(pos, windowLen) {
    .Call(`_binmapr_findWindow`, pos, windowLen)
}

